### ISSUE TITLE
growthbook-cli command is not working after install on Node v14

### ISSUE THREAD

**Issue by sandeep-tiwari-groww** [growthbook/growthbook-cli#28]
I tried `npm install -g growthbook` and cli is installed in my system

but after that cli command is not working. Getting `Error: Cannot find module 'node:os'`
Please refer screenshot attached. 

<img width="1093" alt="Screenshot 2023-04-19 at 5 35 42 PM" src="https://user-images.githubusercontent.com/113884270/233070029-c49c46e3-3bbb-4537-b358-5eab85d01eed.png">

**Comment by tinahollygb** [comment]
Please try with Node version 16+, e.g.:

```sh
nvm install v16.16.0
nvm use v16.16.0
npm i -g growthbook
```

Or the latest LTS:

```sh
nvm install v18.16.0
nvm use v18.16.0
npm i -g growthbook
```

oclif appears to use the `node:` prefixes which were added later (maybe [15.14.0](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V15.md#15.14.0)?)

**Comment by tinahollygb** [comment]
Thanks for this report. I was able to reproduce the failure on Node v14.x and I see it working on Node v16.x and v18.x. 

This version requirement is captured in this PR: https://github.com/growthbook/growthbook/pull/1206

Closing this ticket as we do not intend to support Node 14 for now.
