### ISSUE TITLE
--apiKey and --profile cause follow-up prompts even when arguments are provided.

### ISSUE THREAD

**Issue by AlexHartford** [growthbook/growthbook-cli#36]
I'd like to add something like:
```json
// package.json
"growthbook-type-gen": "npx env-cmd growthbook auth login --apiKey \\${GROWTHBOOK_API_KEY} --profile growthbookrc && growthbook features generate-types --output ./types"
```
This would make it easier to generate types, but the follow-up prompts are not conducive to automated scripts.

Can the CLI arguments work like arguments as documented?

**Comment by tinahollygb** [comment]
We'd welcome the contribution. For example, passing `--apiKey --profile --apiBaseUrl` would be great flags to add, and if they are not included, we can prompt the user. The `metrics create` command is an example where we take command flags or prompt for input if not provided, so if you wanted an example to work from, you can use that.

**Comment by AlexHartford** [comment]
@tinahollygb Are you planning to do a release that includes these changes? I'd like to pull this into my project 😄
